kind: Service
apiVersion: v1
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
  - name: promui
    nodePort: 30700
    protocol: TCP
    port: 9090
    targetPort: 9090
  type: LoadBalancer