apiVersion: v1
kind: Service
metadata:
  labels:
    app: pythonserver
  name: pythonserver
  namespace: default
spec:
  ports:
  - name: pythonserver
    nodePort: 30800
    protocol: TCP
    port: 8001
    targetPort: 8001
  selector:
    app: pythonserver
  type: LoadBalancer